### PR TITLE
Update to 1.16

### PR DESCRIPTION
**Pull request by garagepoort**

### CODE REVIEW

**Comment by Qballl** [comment]
I think this is now taken care of I had already updated to 1.16 just hadn't pushed as I've been busy and then when I'm not I foget

**Comment by Qballl** [comment]
It also looks like some of your changes would break backwards compatiblity

**Comment by garagepoort** [comment]
I know it would break backwards compatibility. It was just an example PR.
But I suggest creating different tags for different spigots versions because you are also breaking backwards compatibility now.

**Comment by Azoraqua** [comment]
Seems rather fair. Good suggestion.

**Comment by garagepoort** [comment]
Well Qball made a good point that spigot is backwards compatible but for me keeping one version is just too restrictive.
So for myself I created a fork which I am developing now. https://github.com/garagepoort/StaffPlusPlus

It's also available on spigot but is still in a very early stage.

**Pull request closed without merging**
