### PR TITLE
Update PlayerJoin.java by removing auto freeze if login attempt takes to long.

### PR DESCRIPTION
**Pull request by semmeess**

### CODE REVIEW

**Comment by Qballl** [comment]
What is the point of doing that?

**Comment by semmeess** [comment]
it at least needs to be configurable, as if freeze is set to open the inventory screen, this is very annoying for legotimate staff members who will then have to close their client to log in, and/or face the punishment of freeze logging.

**Comment by Qballl** [comment]
Alright now that I have some time on my hands I will work on a fix for this

**Comment by Azoraqua** [comment]
@semmeess Will be looked at but this pull-request will not be used, I assume. So I think it's the best to close it.

**Pull request closed without merging**
