### PR TITLE
One big pull-request this time (added utility, changed pom).

### PR DESCRIPTION
**Pull request by Azoraqua**
- Added JsonUtils with `escape()` (As replacement for JSONObject.escape which is/will be removed from 1.14.* and later) (Reference: https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-3-development-builds.369724/)
- Added InventoryUtils (In reference to issue #52).
- Changed pom.xml to make use of a snapshot repository of SpigotMC which contains more artifacts.

### CODE REVIEW

**Comment by Qballl** [comment]
Woah thank you. This really helps especially the ender chest thing I just havent had time to get around to it. The only real thing is there is no need to change the pom so I will probably undo that. My repo is still up the domain just lapse renewing it when I get off work

**Comment by Qballl** [comment]
Also what is your name on spigot

**Comment by Azoraqua** [comment]
It's [Azoraqua](https://www.spigotmc.org/members/azoraqua.262447/).

**Comment by Qballl** [comment]
Alright I be sure sure to give credit where it is due

**Pull request merged**
